version: 2

models:
  - name: rpt_valued_customers
    tests:
      - dbt_utils.equality:
          compare_model: ref('rpt_valued_customers_row_count')
          compare_columns:
            - customer_id