version: 2

models:
    - name: dim_customers
      description: "Business that purchases products with discount and customer's "
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - customer_id
      columns:
          - name: CUSTOMER_ID
            description: "The key column for this table"
            tests:
                - not_null
          - name: CUSTOMER_NAME
            tests:
                - not_null
          - name: FIRST_ORDER_DATE
            description: "The key column for this table"
            tests:
                - not_null
          - name: MOST_RECENT_ORDER_DATE
            description: "The key column for this table"
            tests:
                - not_null
          - name: NUMBER_OF_ORDERS
            description: "The key column for this table"
            tests:
                - not_null
          - name: LIFETIME_VALUE
            description: "The key column for this table"
            tests:
                - not_null

