
version: 2

models:
    - name: rpt_cherished_customers
      description: "Business that purchases products with high discount"
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - order_id
              - item_id
      columns:
          - name: order_id
            description: "The key column for this table"
            tests:
                - not_null
          - name: quantity
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: false
                  where: "order_id > 1"

